Adding missed functions

diff --git a/git_bash b/git_bash
--- a/git_bash
+++ b/git_bash
@@ -122,3 +122,20 @@ function gitC() {
 function gitBH() {
     git reflog | grep checkout | awk '{print $NF}'
 }
+
+function exec() {
+    $@
+    local status=$?
+    if [ $status -ne 0 ]; then
+        error_log "Failed executing $1. Exit code $status"
+        kill -INT $$
+    fi
+}
+
+function info_log() {
+    echo "[INFO] $1"
+}
+
+function error_log() {
+    echo "[ERROR] $1"
+}
